#=================================================
#   Description: Build OpenWrt using GitHub Actions
#   Lisence: MIT
#   Author: P3TERX
#   Blog: https://p3terx.com
#=================================================

name: Build OpenWrt

on: 
  release:
    types: [published]
  push:
    branches: 
      - master
  schedule:
    - cron: 0 0 1 * *
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      run: |
        sudo apt-get update
        sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler

    - name: Clone source code
      run: |
        git clone -b master https://github.com/gw826943555/openwrt openwrt
        cd openwrt/
        git clone https://github.com/Lienol/openwrt-package ./package/lienol
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Custom config file
      run: |
        bash ./mkconfig.sh

    - name: Download package source code
      run: |
        cd openwrt
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Build CM520
      run: |
        bash ./mkconfig.sh CONFIG_TARGET_ipq40xx_generic_DEVICE_mobipromo_cm520-79f=y
        cd openwrt
        echo -e "$(nproc) thread build."
        make -j$(nproc) V=s

    - name: Build R619AC
      run: |
        bash ./mkconfig.sh CONFIG_TARGET_ipq40xx_generic_DEVICE_p2w_r619ac-128m=y
        cd openwrt
        echo -e "$(nproc) thread build."
        make -j$(nproc) V=s

    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: OpenWrt
        path: openwrt/bin
