#=================================================
#   Description: Build OpenWrt using GitHub Actions
#   Lisence: MIT
#   Author: P3TERX
#   Blog: https://p3terx.com
#=================================================

name: Build OpenWrt

on: 
  release:
    types: [published]
  push:
    branches: 
      - master
  schedule:
    - cron: 0 0 1 * *
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      run: |
        sudo apt-get update
        sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
        sudo apt-get -y autoremove --purge
        sudo apt-get clean
	# 利用挂载在 /mnt/ 的 14G 额外空间:
        sudo mkdir -p -m 777 /mnt/openwrt/bin /mnt/openwrt/build_dir/host /mnt/openwrt/build_dir/hostpkg /mnt/openwrt/dl /mnt/openwrt/feeds /mnt/openwrt/staging_dir
        ln -s /mnt/openwrt/bin ./bin
        mkdir -p ./build_dir/host && ln -s /mnt/openwrt/build_dir/host ./build_dir/host
        mkdir -p ./build_dir/host && ln -s /mnt/openwrt/build_dir/hostpkg ./build_dir/hostpkg
        ln -s /mnt/openwrt/dl ./dl
        ln -s /mnt/openwrt/feeds ./feeds
        ln -s /mnt/openwrt/staging_dir ./staging_dir

        df -h
    - name: Clone source code
      run: |
        git clone -b master https://github.com/gw826943555/openwrt openwrt
        cd openwrt/
        git clone --recursive https://github.com/gw826943555/openwrt-packages-misc ./package/misc
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Custom config file
      run: |
        bash ./custom.sh
        bash ./mkconfig.sh

    - name: Download package source code
      run: |
        cd openwrt
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Build CM520
      run: |
        bash ./mkconfig.sh cm520
        cd openwrt
        echo -e "$(nproc) thread build."
        make -j$(nproc) V=s

    - name: Build R619AC
      run: |
        bash ./mkconfig.sh
        cd openwrt
        echo -e "$(nproc) thread build."
        make -j$(nproc) V=s

    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: OpenWrt
        path: openwrt/bin/targets
